# Generated by Django 5.2.12 on 2026-03-06 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_ctdt_matrices'),
        ('rbac', '0002_auditlog_permission_role_rolepermission_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, verbose_name='Tên file')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='File upload')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('PREVIEW', 'Xem trước'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Tiến độ (%)')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu đã phân tích')),
                ('result', models.JSONField(blank=True, help_text='{program_id, warnings, errors}', null=True, verbose_name='Kết quả')),
                ('error_message', models.TextField(blank=True, verbose_name='Thông báo lỗi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.department', verbose_name='Khoa')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_tasks', to='programs.trainingprogram', verbose_name='CTĐT đã tạo')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Tác vụ import',
                'verbose_name_plural': 'Tác vụ import',
                'ordering': ['-created_at'],
            },
        ),
    ]
