# Generated by Django 5.2.12 on 2026-03-06 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên đơn vị')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rbac.department', verbose_name='Đơn vị cha')),
            ],
            options={
                'verbose_name': 'Đơn vị',
                'verbose_name_plural': 'Đơn vị',
                'ordering': ['code'],
            },
        ),
    ]
