# Generated by Django 5.2.12 on 2026-03-06 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('SUBMIT', 'Nộp duyệt'), ('APPROVE', 'Phê duyệt'), ('REJECT', 'Từ chối'), ('ROLLBACK', 'Quay lại phiên bản')], max_length=20, verbose_name='Hành động')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.UUIDField(verbose_name='ID đối tượng')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu cũ')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mới')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'Nhật ký',
                'verbose_name_plural': 'Nhật ký',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã quyền')),
                ('name', models.CharField(max_length=100, verbose_name='Tên quyền')),
                ('module', models.CharField(choices=[('programs', 'Chương trình đào tạo'), ('plo', 'Chuẩn đầu ra'), ('syllabus', 'Đề cương chi tiết'), ('courses', 'Học phần'), ('rbac', 'Quản trị hệ thống')], max_length=20, verbose_name='Module')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Quyền',
                'verbose_name_plural': 'Quyền',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã vai trò')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vai trò')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('level', models.IntegerField(default=0, help_text='Thứ tự trong hệ thống phê duyệt', verbose_name='Cấp bậc')),
                ('is_system', models.BooleanField(default=False, help_text='Vai trò hệ thống không thể xóa', verbose_name='Vai trò hệ thống')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Quyền của vai trò',
                'verbose_name_plural': 'Quyền của vai trò',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Vai trò người dùng',
                'verbose_name_plural': 'Vai trò người dùng',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên tiếng Anh'),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('KHOA', 'Khoa'), ('VIEN', 'Viện'), ('PHONG', 'Phòng'), ('TRUNG_TAM', 'Trung tâm'), ('BAN_GIAM_HIEU', 'Ban Giám Hiệu')], default='KHOA', max_length=20, verbose_name='Loại đơn vị'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.department', verbose_name='Đơn vị cha'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='rbac_depart_code_a07407_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='rbac_depart_type_bbae38_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='Quyền'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='Vai trò'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='rbac.RolePermission', to='rbac.permission', verbose_name='Quyền hạn'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người gán'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(help_text='Vai trò này có hiệu lực trong đơn vị nào', on_delete=django.db.models.deletion.CASCADE, to='rbac.department', verbose_name='Đơn vị'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='Vai trò'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='rbac_auditl_entity__bb92f6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='rbac_auditl_user_id_6458e0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='rbac_auditl_created_d2a5bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='rbac_userro_user_id_f47914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'department')},
        ),
    ]
