# Generated by Django 5.2.12 on 2026-03-06 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auditlog_permission_role_rolepermission_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLearningOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Mã PLO')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('competency_level', models.DecimalField(decimal_places=1, default=0.0, help_text='0.0 - 6.0', max_digits=3, verbose_name='Mức năng lực (Bloom)')),
                ('competency_label', models.CharField(blank=True, max_length=50, verbose_name='Nhãn năng lực')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Chuẩn đầu ra (PLO)',
                'verbose_name_plural': 'Chuẩn đầu ra (PLO)',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProgramObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Mã PO')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Mục tiêu đào tạo (PO)',
                'verbose_name_plural': 'Mục tiêu đào tạo (PO)',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='PLOPOMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programlearningoutcome', verbose_name='PLO')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programobjective', verbose_name='PO')),
            ],
            options={
                'verbose_name': 'PO-PLO Mapping',
                'verbose_name_plural': 'PO-PLO Mapping',
                'unique_together': {('plo', 'po')},
            },
        ),
        migrations.AddField(
            model_name='programlearningoutcome',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='plos', through='programs.PLOPOMapping', to='programs.programobjective', verbose_name='Mục tiêu liên quan'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name_vi', models.CharField(max_length=300, verbose_name='Tên chương trình (VN)')),
                ('program_name_en', models.CharField(blank=True, max_length=300, verbose_name='Tên chương trình (EN)')),
                ('program_code', models.CharField(max_length=20, unique=True, verbose_name='Mã chương trình')),
                ('degree_name', models.CharField(max_length=200, verbose_name='Tên bằng cấp')),
                ('education_level', models.CharField(choices=[('DAI_HOC', 'Đại học'), ('THAC_SI', 'Thạc sĩ'), ('TIEN_SI', 'Tiến sĩ')], default='DAI_HOC', max_length=20, verbose_name='Trình độ đào tạo')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='Tổng số tín chỉ')),
                ('training_duration', models.CharField(default='4 năm', max_length=50, verbose_name='Thời gian đào tạo')),
                ('decision_number', models.CharField(blank=True, max_length=100, verbose_name='Số quyết định')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Ngày quyết định')),
                ('issuing_institution', models.CharField(default='Trường Đại học Công nghệ TP.HCM', max_length=200, verbose_name='Nơi ban hành')),
                ('general_objective', models.TextField(blank=True, verbose_name='Mục tiêu chung')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='Điều kiện tuyển sinh')),
                ('graduation_requirements', models.TextField(blank=True, verbose_name='Điều kiện tốt nghiệp')),
                ('career_opportunities', models.TextField(blank=True, verbose_name='Vị trí việc làm')),
                ('further_education', models.TextField(blank=True, verbose_name='Khả năng học tập nâng cao')),
                ('teaching_methodology', models.TextField(blank=True, verbose_name='Phương pháp giảng dạy')),
                ('assessment_methodology', models.TextField(blank=True, verbose_name='Phương pháp đánh giá')),
                ('implementation_guide', models.TextField(blank=True, verbose_name='Hướng dẫn thực hiện')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('SUBMITTED', 'Đã nộp'), ('KHOA_REVIEWING', 'Khoa đang xét duyệt'), ('KHOA_APPROVED', 'Khoa đã duyệt'), ('PDT_REVIEWING', 'Phòng ĐT đang xét duyệt'), ('PDT_APPROVED', 'Phòng ĐT đã duyệt'), ('BGH_REVIEWING', 'BGH đang xét duyệt'), ('PUBLISHED', 'Đã công bố'), ('REVISION_REQUIRED', 'Cần chỉnh sửa')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_programs', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa cuối')),
                ('managing_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_programs', to='rbac.department', verbose_name='Khoa quản lý')),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Chương trình đào tạo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='programobjective',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='programs.trainingprogram', verbose_name='Chương trình'),
        ),
        migrations.AddField(
            model_name='programlearningoutcome',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plos', to='programs.trainingprogram', verbose_name='Chương trình'),
        ),
        migrations.CreateModel(
            name='KnowledgeBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên khối kiến thức')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='Tổng tín chỉ')),
                ('required_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ bắt buộc')),
                ('elective_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ tự chọn')),
                ('percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tỷ lệ (%)')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='programs.knowledgeblock', verbose_name='Khối cha')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_blocks', to='programs.trainingprogram', verbose_name='Chương trình')),
            ],
            options={
                'verbose_name': 'Khối kiến thức',
                'verbose_name_plural': 'Khối kiến thức',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Mã PI')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_indicators', to='programs.programlearningoutcome', verbose_name='PLO')),
            ],
            options={
                'verbose_name': 'Chỉ số đo lường (PI)',
                'verbose_name_plural': 'Chỉ số đo lường (PI)',
                'ordering': ['order_index'],
                'unique_together': {('plo', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['program_code'], name='programs_tr_program_702380_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['status'], name='programs_tr_status_5948ce_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['managing_department'], name='programs_tr_managin_7bf708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programobjective',
            unique_together={('program', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='programlearningoutcome',
            unique_together={('program', 'code')},
        ),
    ]
