# Generated by Django 5.2.12 on 2026-03-06 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('rbac', '0002_auditlog_permission_role_rolepermission_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm học phần',
                'verbose_name_plural': 'Nhóm học phần',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã học phần')),
                ('name_vi', models.CharField(max_length=300, verbose_name='Tên học phần (VN)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Tên học phần (EN)')),
                ('total_credits', models.PositiveIntegerField(verbose_name='Tổng tín chỉ')),
                ('theory_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ lý thuyết')),
                ('practice_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ thực hành')),
                ('project_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ đồ án')),
                ('internship_credits', models.PositiveIntegerField(default=0, verbose_name='Tín chỉ thực tập')),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng giờ')),
                ('theory_hours', models.PositiveIntegerField(default=0, verbose_name='Giờ lý thuyết')),
                ('practice_hours', models.PositiveIntegerField(default=0, verbose_name='Giờ thực hành')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tóm tắt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('managing_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='rbac.department', verbose_name='Khoa quản lý')),
                ('course_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='programs.coursegroup', verbose_name='Nhóm học phần')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Học phần',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='VD: I.01, II.03', max_length=10, verbose_name='Số thứ tự')),
                ('is_required', models.BooleanField(default=True, help_text='Bắt buộc / Tự chọn', verbose_name='Bắt buộc')),
                ('semester', models.PositiveIntegerField(blank=True, help_text='1-8', null=True, verbose_name='Học kỳ khuyến nghị')),
                ('batch', models.CharField(blank=True, help_text='A hoặc B', max_length=1, verbose_name='Đợt')),
                ('software_required', models.CharField(blank=True, max_length=200, verbose_name='Phần mềm yêu cầu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='programs.course', verbose_name='Học phần')),
                ('knowledge_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses', to='programs.knowledgeblock', verbose_name='Khối kiến thức')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='programs.trainingprogram', verbose_name='Chương trình')),
            ],
            options={
                'verbose_name': 'Học phần trong CTĐT',
                'verbose_name_plural': 'Học phần trong CTĐT',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PREREQUISITE', 'Học trước'), ('COREQUISITE', 'Song hành')], default='PREREQUISITE', max_length=20, verbose_name='Loại')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course', verbose_name='Học phần tiên quyết')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='programs.programcourse', verbose_name='Học phần trong CTĐT')),
            ],
            options={
                'verbose_name': 'Điều kiện tiên quyết',
                'verbose_name_plural': 'Điều kiện tiên quyết',
            },
        ),
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_number', models.PositiveIntegerField(help_text='1-8', verbose_name='Học kỳ')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='programs.trainingprogram', verbose_name='Chương trình')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programcourse', verbose_name='Học phần trong CTĐT')),
            ],
            options={
                'verbose_name': 'Kế hoạch học kỳ',
                'verbose_name_plural': 'Kế hoạch học kỳ',
                'ordering': ['semester_number', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='programs_co_code_194299_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['managing_department'], name='programs_co_managin_e63f38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('program_course', 'prerequisite_course')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together={('program', 'program_course')},
        ),
    ]
