# Generated by Django 5.2.12 on 2026-03-06 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_course_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePLOContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_level', models.PositiveIntegerField(choices=[(0, 'Không đóng góp'), (1, 'Thấp'), (2, 'Trung bình'), (3, 'Cao')], default=0, verbose_name='Mức đóng góp')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_contributions', to='programs.performanceindicator', verbose_name='Chỉ số PI')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_contributions', to='programs.programcourse', verbose_name='Học phần trong CTĐT')),
            ],
            options={
                'verbose_name': 'Đóng góp HP-PLO-PI',
                'verbose_name_plural': 'Đóng góp HP-PLO-PI',
                'indexes': [models.Index(fields=['program_course'], name='programs_co_program_7a6dfa_idx'), models.Index(fields=['pi'], name='programs_co_pi_id_9240be_idx')],
                'unique_together': {('program_course', 'pi')},
            },
        ),
        migrations.CreateModel(
            name='PLOAssessmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributing_courses_text', models.TextField(blank=True, help_text='VD: POS104 POS105 POS106', verbose_name='HP đóng góp')),
                ('direct_evidence', models.CharField(blank=True, help_text='VD: Chuyên cần, Báo cáo cuối kỳ', max_length=200, verbose_name='Minh chứng trực tiếp')),
                ('assessment_tool', models.CharField(blank=True, help_text='VD: Điểm chuyên cần, Rubric', max_length=200, verbose_name='Công cụ đánh giá')),
                ('expected_standard', models.CharField(blank=True, help_text='VD: Tối thiểu 70% người học đáp ứng', max_length=200, verbose_name='Tiêu chuẩn kỳ vọng')),
                ('assessment_schedule', models.CharField(blank=True, help_text='VD: HK1 / năm 3', max_length=100, verbose_name='Lịch đánh giá')),
                ('responsible_lecturer', models.CharField(blank=True, max_length=200, verbose_name='Giảng viên phụ trách')),
                ('managing_unit', models.CharField(blank=True, max_length=200, verbose_name='Đơn vị quản lý')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_plans', to='programs.performanceindicator', verbose_name='Chỉ số PI')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_plans', to='programs.trainingprogram', verbose_name='Chương trình')),
                ('sample_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_samples', to='programs.course', verbose_name='HP lấy mẫu')),
            ],
            options={
                'verbose_name': 'Kế hoạch đánh giá PLO',
                'verbose_name_plural': 'Kế hoạch đánh giá PLO',
                'ordering': ['pi__plo__order_index', 'pi__order_index'],
                'indexes': [models.Index(fields=['program'], name='programs_pl_program_609a0c_idx'), models.Index(fields=['pi'], name='programs_pl_pi_id_49cb77_idx')],
            },
        ),
    ]
