# Generated by Django 5.2.12 on 2026-03-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_ctdt_matrices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_group',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='elective_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Tín chỉ tự chọn'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='knowledge_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='programs.knowledgeblock', verbose_name='Khối kiến thức'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='total_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng tín chỉ'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses', to='programs.coursegroup', verbose_name='Nhóm học phần'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên nhóm'),
        ),
    ]
