# Generated by Django 5.2.12 on 2026-03-10 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_course_course_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeblock',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_blocks_legacy', to='programs.trainingprogram', verbose_name='Chương trình (Legacy)'),
        ),
        migrations.CreateModel(
            name='TrainingProgramVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='VD: 2024-2025', max_length=20, verbose_name='Năm học')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('ACTIVE', 'Đang áp dụng'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='programs.trainingprogram', verbose_name='Chương trình')),
            ],
            options={
                'verbose_name': 'Phiên bản CTĐT',
                'verbose_name_plural': 'Phiên bản CTĐT',
                'ordering': ['-academic_year'],
                'unique_together': {('program', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='knowledgeblock',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_blocks', to='programs.trainingprogramversion', verbose_name='Phiên bản CTĐT'),
        ),
    ]
