# Generated by Django 5.2.12 on 2026-03-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_add_training_program_version'),
    ]

    operations = [
    ]
