# Generated by Django 5.2.12 on 2026-03-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_create_default_versions_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='knowledgeblock',
            name='program',
        ),
        migrations.AddField(
            model_name='programcourse',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='programs.trainingprogramversion', verbose_name='Phiên bản CTĐT'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='programs.trainingprogramversion', verbose_name='Phiên bản CTĐT'),
        ),
        migrations.AlterField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses_legacy', to='programs.trainingprogram', verbose_name='Chương trình (Legacy)'),
        ),
        migrations.AlterField(
            model_name='semesterplan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_plans_legacy', to='programs.trainingprogram', verbose_name='Chương trình (Legacy)'),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('version', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together={('version', 'program_course')},
        ),
    ]
