# Generated by Django 5.2.12 on 2026-03-07 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auditlog_permission_role_rolepermission_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(verbose_name='Số bước')),
                ('step_name', models.CharField(max_length=100, verbose_name='Tên bước')),
                ('required_department_scope', models.BooleanField(default=True, help_text='True = phải cùng department với entity. False = cross-department (PDT, BGH)', verbose_name='Phạm vi đơn vị')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ đến lượt'), ('IN_REVIEW', 'Đang xét duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('SKIPPED', 'Bỏ qua')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('action_comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản (locking)')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('required_role', models.ForeignKey(help_text='Vai trò cần có để duyệt bước này', on_delete=django.db.models.deletion.PROTECT, to='rbac.role', verbose_name='Vai trò cần có')),
            ],
            options={
                'verbose_name': 'Bước phê duyệt',
                'verbose_name_plural': 'Bước phê duyệt',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workflows.approvalcomment', verbose_name='Phản hồi cho')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflows.approvalstep', verbose_name='Bước')),
            ],
            options={
                'verbose_name': 'Bình luận phê duyệt',
                'verbose_name_plural': 'Bình luận phê duyệt',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('TrainingProgram', 'Chương trình đào tạo'), ('ProgramLearningOutcome', 'Chuẩn đầu ra'), ('Syllabus', 'Đề cương chi tiết')], max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='ID đối tượng')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('REJECTED', 'Bị từ chối'), ('CANCELLED', 'Đã hủy')], default='IN_PROGRESS', max_length=20, verbose_name='Trạng thái')),
                ('current_step_number', models.PositiveIntegerField(default=1, verbose_name='Bước hiện tại')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='Tổng số bước')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Quy trình phê duyệt',
                'verbose_name_plural': 'Quy trình phê duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvalworkflow', verbose_name='Quy trình'),
        ),
        migrations.CreateModel(
            name='EntityVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('TrainingProgram', 'Chương trình đào tạo'), ('ProgramLearningOutcome', 'Chuẩn đầu ra'), ('Syllabus', 'Đề cương chi tiết')], max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.UUIDField(verbose_name='ID đối tượng')),
                ('version_number', models.PositiveIntegerField(verbose_name='Số phiên bản')),
                ('snapshot_data', models.JSONField(default=dict, help_text='Full serialized entity data at approval time', verbose_name='Dữ liệu snapshot')),
                ('change_summary', models.TextField(blank=True, verbose_name='Tóm tắt thay đổi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_versions', to='workflows.approvalworkflow', verbose_name='Quy trình tạo phiên bản')),
            ],
            options={
                'verbose_name': 'Phiên bản tài liệu',
                'verbose_name_plural': 'Phiên bản tài liệu',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['entity_type', 'entity_id'], name='workflows_a_entity__6af360_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status'], name='workflows_a_status_bb0012_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['initiated_by', '-created_at'], name='workflows_a_initiat_515bb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('entity_type', 'entity_id'), name='unique_active_workflow_per_entity'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['status', 'required_role'], name='workflows_a_status_ae215c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='entityversion',
            index=models.Index(fields=['entity_type', 'entity_id', '-version_number'], name='workflows_e_entity__2f6d13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityversion',
            unique_together={('entity_type', 'entity_id', 'version_number')},
        ),
    ]
