# Generated by Django 5.2.12 on 2026-03-06 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0003_ctdt_matrices'),
        ('rbac', '0002_auditlog_permission_role_rolepermission_userrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='VD: TrainingProgram', max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.UUIDField(verbose_name='ID đối tượng')),
                ('current_step', models.PositiveIntegerField(default=0, verbose_name='Bước hiện tại')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('IN_PROGRESS', 'Đang xét duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
            ],
            options={
                'verbose_name': 'Quy trình phê duyệt',
                'verbose_name_plural': 'Quy trình phê duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(help_text='1=Khoa, 2=Phòng ĐT, 3=BGH', verbose_name='Số bước')),
                ('step_name', models.CharField(max_length=100, verbose_name='Tên bước')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối'), ('SKIPPED', 'Bỏ qua')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.role', verbose_name='Vai trò duyệt')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvalworkflow', verbose_name='Quy trình')),
            ],
            options={
                'verbose_name': 'Bước phê duyệt',
                'verbose_name_plural': 'Bước phê duyệt',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='Số phiên bản')),
                ('snapshot_data', models.JSONField(help_text='Full CTĐT data at approval time', verbose_name='Dữ liệu snapshot')),
                ('change_summary', models.TextField(blank=True, verbose_name='Tóm tắt thay đổi')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='programs.trainingprogram', verbose_name='Chương trình')),
            ],
            options={
                'verbose_name': 'Phiên bản CTĐT',
                'verbose_name_plural': 'Phiên bản CTĐT',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['entity_type', 'entity_id'], name='workflows_a_entity__6af360_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status'], name='workflows_a_status_bb0012_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('workflow', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='programversion',
            unique_together={('program', 'version_number')},
        ),
    ]
