# Generated by Django 5.2.12 on 2026-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programversion',
            name='snapshot_data',
            field=models.JSONField(default=dict, help_text='Full CTĐT data at approval time', verbose_name='Dữ liệu snapshot'),
        ),
    ]
